name: rubu
description: A new Flutter project.

publish_to: "none"

version: 2.1.0+315

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.5
  flutter_svg: ^2.0.4
  flutter_switch: ^0.3.2
  get_it: ^8.0.0
  get_storage: ^2.1.1
  readmore: ^3.0.0
  webview_flutter: ^4.2.2
  html: ^0.15.4
  cached_network_image: ^3.2.3
  google_sign_in: ^6.1.0
  timeago: ^3.3.0
  image: ^4.0.15
  url_launcher: ^6.1.11
  share_plus: ^10.0.0
  image_picker:
    path: ./packages/image_picker-1.1.2
  image_cropper: ^8.0.2
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  flutter_local_notifications: ^17.2.1+2
  http: ^1.1.2
  scrollable_positioned_list: ^0.3.8
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  path_provider: ^2.0.15
  country: ^4.1.5
  collection: ^1.17.0
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^11.1.0
  pinch_zoom_release_unzoom: ^1.0.1
  flutter_branch_sdk: ^8.2.0
  flutter_spinkit: ^5.2.0
  mime: ^2.0.0
  video_player:
    path: ./packages/video_player-2.9.1
  video_editor:
    path: ./packages/video_editor-3.0.0
  video_thumbnail:
    path: ./packages/video_thumbnail-0.5.3
  fraction: ^5.0.2
  visibility_detector: ^0.4.0+2
  ffmpeg_kit_flutter: ^6.0.3
  preload_page_view: ^0.2.0
  image_editor_plus:
    path: ./packages/image_editor_plus-1.0.6

  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  firebase_storage: ^12.3.1
  firebase_analytics: ^11.3.2
  firebase_messaging: ^15.1.2
  firebase_performance: ^0.10.0+7
  intercom_flutter: ^9.0.7
  flutter_cache_manager: ^3.3.1
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  web_scraper: ^0.1.4
  pkce: ^1.1.0+1
  auth0_flutter: ^1.6.0
  phone_text_field: ^0.0.7
  pin_code_fields: ^8.0.1
  network_info_plus: ^6.0.1
  flutter_typeahead: ^5.2.0
  bad_words: ^0.3.0
  uuid: ^4.4.2
  flutter_timezone: ^3.0.1
  dots_indicator: ^3.0.0
  intl: ^0.19.0
  adjust_sdk: ^5.0.2
  internet_connection_checker_plus: ^2.5.2
  iconsax_plus: ^1.0.0
  cloud_functions: ^5.2.0
  phone_form_field: ^10.0.2
  pigeon: ^22.7.0
  flutter_email_sender: ^7.0.0

  timezone: any
  purchases_flutter: ^8.5.0
  package_info_plus: ^8.2.1
  flutter_stripe: ^11.4.0
  pay: ^3.2.0
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.4
  intl_utils: ^2.8.7

  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1
  build_runner: ^2.4.13

dependency_overrides:
  intl: any
  http: ^0.13.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/evershop_app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

    - assets/images/welcome/

    - assets/images/auth/

    - assets/images/feed/post/
    - assets/images/feed/trending_influencers/
    - assets/images/feed/influencer_profile/
    - assets/images/feed/influencer_profile/recent/
    - assets/images/feed/influencer_profile/collections/
    - assets/images/feed/influencer_profile/collections/fashion/

    - assets/images/home/
    - assets/images/home/bottom_navigation_bar/

    - assets/images/search/
    - assets/images/search/discover/
    - assets/images/search/on_interest/
    - assets/images/search/tabs/

    - assets/images/liked/

    - assets/images/settings/
    - assets/images/settings/influencer/

    - assets/images/influencer/
    - assets/images/influencer/socials/
    - assets/images/influencer/profile/
    - assets/images/influencer/add_product/

    - assets/images/account/
    - assets/images/account/backgrounds/
    - assets/images/account/socials/

    - assets/videos/
